import "./globals.sass"

export const metadata = {
  title: "Landrup Dans",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <body>
        {children}
      </body>
    </html>
  )
}